### ISSUE TITLE
Cirno-Fumo-Scrap-mod v1.1. has no assets, mod not loading

### ISSUE THREAD

**Issue by matheusAFreitas** [Badhamknibbs/Cirno-Fumo-Scrap-mod_LC#2]
![image](https://github.com/Badhamknibbs/Cirno-Fumo-Scrap-mod_LC/assets/87462747/b14761b7-245a-4676-aacc-68ef960a63a7)
![image](https://github.com/Badhamknibbs/Cirno-Fumo-Scrap-mod_LC/assets/87462747/15847ece-0e24-41bd-9d51-bdc4ffd29efa)
![image](https://github.com/Badhamknibbs/Cirno-Fumo-Scrap-mod_LC/assets/87462747/7198024a-30b6-4c86-aa7a-834d676458f1)

**Comment by Badhamknibbs** [comment]
Ah bugger, guessing an issue with paths since I switched environment; I'll look into it this arvo (about 6 hours). For now 1.0.1 will have to do, which only works for the host (aka solo only)

**Comment by matheusAFreitas** [comment]
nevermind, I found the problem, its a mod conflict, the brutal company mod  dont let other mods to load

**Comment by matheusAFreitas** [comment]
I thought it was a mod conflict, but apparently not

**Comment by Badhamknibbs** [comment]
Fixed in 1.2.0, along with working in multiplayer properly now
